apiVersion: apps/v1
kind: Deployment
metadata:
name: pythontest
spec:
replicas: 2
selector:
matchLabels:
app: pythontest
strategy:
type: Recreate
template:
metadata:
labels:
app: pythontest
containers:
- image: localhost:5000/pythontest
imagePullPolicy: IfNotPresent
name: pythontest
command: ["python"]
args: ["./helloworld.py"]
env:
- name: CONTAINER_PYTHON_VAR
value: "Echo string from kubernetes"
ports:
- containerPort: 31313
name: pythontest
